name: scaffold_cli
description: A CLI tool to scaffold Flutter projects with popular folder structures and state management.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  ansi_styles: ^0.3.1
  path: ^1.9.0
  process_run: ^0.13.0

dev_dependencies:
  lints: ^3.0.0

executables:
  scaffold: scaffold
